### ISSUE TITLE
Add Murre perhaps

### ISSUE THREAD

**Issue by mikahama** [Helsinki-NLP/finlandsvensk-AI#1]
Wow, what a cool listing. We did recently normalization for finlandssvenska and released the models as a part of Murre ([https://github.com/mikahama/murre](https://github.com/mikahama/murre)). Maybe it could be added to the list as well?

**Comment by jorgtied** [comment]
Done - the list was not really adopted by the people from magma, unfortunately. Maybe we can still keep it running but I am not maintaining it actively .... at least at the moment.
